version: '3.8'

services:

  web:
    build: ./data_access
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./data_access:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL=postgresql://srv:0@localhost:5159/Dse
    depends_on:
      - db

  db:
    image: postgres:13.4
    ports:
      - 5159:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=srv
      - POSTGRES_PASSWORD=0
      - POSTGRES_DB=Dse

